
# This file is automatically generated, you probably don't want to edit this

chisqsrdOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqsrdOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rows = NULL,
            cols = NULL,
            counts = NULL,
            alpha = 0.05,
            doPruning = TRUE,
            showMethodInfo = TRUE, ...) {

            super$initialize(
                package="ChiSquaredTools",
                name="chisqsrd",
                requiresData=TRUE,
                ...)

            private$..rows <- jmvcore::OptionVariable$new(
                "rows",
                rows,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..cols <- jmvcore::OptionVariable$new(
                "cols",
                cols,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                suggested=list(
                    "continuous"))
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                min=0.001,
                max=0.2,
                default=0.05)
            private$..doPruning <- jmvcore::OptionBool$new(
                "doPruning",
                doPruning,
                default=TRUE)
            private$..showMethodInfo <- jmvcore::OptionBool$new(
                "showMethodInfo",
                showMethodInfo,
                default=TRUE)

            self$.addOption(private$..rows)
            self$.addOption(private$..cols)
            self$.addOption(private$..counts)
            self$.addOption(private$..alpha)
            self$.addOption(private$..doPruning)
            self$.addOption(private$..showMethodInfo)
        }),
    active = list(
        rows = function() private$..rows$value,
        cols = function() private$..cols$value,
        counts = function() private$..counts$value,
        alpha = function() private$..alpha$value,
        doPruning = function() private$..doPruning$value,
        showMethodInfo = function() private$..showMethodInfo$value),
    private = list(
        ..rows = NA,
        ..cols = NA,
        ..counts = NA,
        ..alpha = NA,
        ..doPruning = NA,
        ..showMethodInfo = NA)
)

chisqsrdResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqsrdResults",
    inherit = jmvcore::Group,
    active = list(
        originalTable = function() private$.items[["originalTable"]],
        summaryTable = function() private$.items[["summaryTable"]],
        pruningTable = function() private$.items[["pruningTable"]],
        rowMergeTable = function() private$.items[["rowMergeTable"]],
        rowGroupsTable = function() private$.items[["rowGroupsTable"]],
        rowReducedTable = function() private$.items[["rowReducedTable"]],
        colMergeTable = function() private$.items[["colMergeTable"]],
        colGroupsTable = function() private$.items[["colGroupsTable"]],
        colReducedTable = function() private$.items[["colReducedTable"]],
        reducedTable = function() private$.items[["reducedTable"]],
        methodInfo = function() private$.items[["methodInfo"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Simultaneous Reduction of Dimension (SRD)")
            self$add(jmvcore::Table$new(
                options=options,
                name="originalTable",
                title="Original Contingency Table",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts"),
                columns=list()))
            self$add(jmvcore::Table$new(
                options=options,
                name="summaryTable",
                title="SRD Summary",
                refs=list(
                    "ortontyers1991",
                    "greenacre1984"),
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "alpha",
                    "doPruning"),
                columns=list(
                    list(
                        `name`="stage", 
                        `title`="Stage", 
                        `type`="text"),
                    list(
                        `name`="nRows", 
                        `title`="Rows", 
                        `type`="integer"),
                    list(
                        `name`="nCols", 
                        `title`="Columns", 
                        `type`="integer"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="totalN", 
                        `title`="Total N", 
                        `type`="number"),
                    list(
                        `name`="nPercent", 
                        `title`="% N Retained", 
                        `type`="number"),
                    list(
                        `name`="chiSquare", 
                        `title`="\u03C7\u00B2", 
                        `type`="number"),
                    list(
                        `name`="chiPercent", 
                        `title`="% \u03C7\u00B2 Retained", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="pruningTable",
                title="Pruning Details",
                visible="(doPruning)",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "alpha",
                    "doPruning"),
                columns=list(
                    list(
                        `name`="dimension", 
                        `title`="Dimension", 
                        `type`="text"),
                    list(
                        `name`="category", 
                        `title`="Category", 
                        `type`="text"),
                    list(
                        `name`="weight", 
                        `title`="Weight", 
                        `type`="number"),
                    list(
                        `name`="criticalWeight", 
                        `title`="Critical Weight", 
                        `type`="number"),
                    list(
                        `name`="reason", 
                        `title`="Reason", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="rowMergeTable",
                title="Row Merge History",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "alpha",
                    "doPruning"),
                columns=list(
                    list(
                        `name`="step", 
                        `title`="Step", 
                        `type`="integer"),
                    list(
                        `name`="item1", 
                        `title`="Item 1", 
                        `type`="text"),
                    list(
                        `name`="item2", 
                        `title`="Item 2", 
                        `type`="text"),
                    list(
                        `name`="weightedDist", 
                        `title`="Weighted \u03C7\u00B2", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="pValue", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="decision", 
                        `title`="Decision", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="rowGroupsTable",
                title="Final Row Groups",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "alpha",
                    "doPruning"),
                columns=list(
                    list(
                        `name`="groupLabel", 
                        `title`="Group Label", 
                        `type`="text"),
                    list(
                        `name`="members", 
                        `title`="Original Members", 
                        `type`="text"),
                    list(
                        `name`="nMembers", 
                        `title`="N Members", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="rowReducedTable",
                title="Row-Grouped Table",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "alpha",
                    "doPruning"),
                columns=list()))
            self$add(jmvcore::Table$new(
                options=options,
                name="colMergeTable",
                title="Column Merge History",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "alpha",
                    "doPruning"),
                columns=list(
                    list(
                        `name`="step", 
                        `title`="Step", 
                        `type`="integer"),
                    list(
                        `name`="item1", 
                        `title`="Item 1", 
                        `type`="text"),
                    list(
                        `name`="item2", 
                        `title`="Item 2", 
                        `type`="text"),
                    list(
                        `name`="weightedDist", 
                        `title`="Weighted \u03C7\u00B2", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="pValue", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="decision", 
                        `title`="Decision", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="colGroupsTable",
                title="Final Column Groups",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "alpha",
                    "doPruning"),
                columns=list(
                    list(
                        `name`="groupLabel", 
                        `title`="Group Label", 
                        `type`="text"),
                    list(
                        `name`="members", 
                        `title`="Original Members", 
                        `type`="text"),
                    list(
                        `name`="nMembers", 
                        `title`="N Members", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="colReducedTable",
                title="Column-Grouped Table",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "alpha",
                    "doPruning"),
                columns=list()))
            self$add(jmvcore::Table$new(
                options=options,
                name="reducedTable",
                title="Reduced Contingency Table",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "alpha",
                    "doPruning"),
                columns=list()))
            self$add(jmvcore::Html$new(
                options=options,
                name="methodInfo",
                title="Method Details",
                visible="(showMethodInfo)",
                clearWith=list(
                    "alpha")))}))

chisqsrdBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqsrdBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ChiSquaredTools",
                name = "chisqsrd",
                version = c(1,0,0),
                options = options,
                results = chisqsrdResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Simultaneous Reduction of Dimension (SRD)
#'
#' Simultaneous Reduction of Dimension (SRD) for sparse contingency tables
#' using the Orton & Tyers (1991) method.
#' 
#' Provides:
#' - Pruning of categories too small to contribute meaningful information
#' - Iterative merging of statistically indistinguishable rows and columns
#' - Chi-squared distance-based similarity assessment
#' - Significance testing for each proposed merge
#' - Reduced contingency table with composite category labels
#' - Detailed merge history with p-values
#' 
#' The method addresses sparse tables where many cells have small or zero 
#' counts, which inflate degrees of freedom and mask genuine patterns. 
#' Unlike hierarchical clustering which merges greedily, SRD only merges 
#' categories that are statistically indistinguishable at the specified 
#' alpha level.
#' 
#'
#' @examples
#' # Basic SRD analysis
#' chisqsrd(
#'     data = mydata,
#'     rows = 'fabric',
#'     cols = 'form',
#'     alpha = 0.05
#' )
#'
#' # With pruning disabled
#' chisqsrd(
#'     data = mydata,
#'     rows = 'fabric',
#'     cols = 'form',
#'     doPruning = FALSE,
#'     alpha = 0.05
#' )
#'
#' @param data the data as a data frame
#' @param rows a string naming the variable for rows in the contingency table
#'   (must be a factor)
#' @param cols a string naming the variable for columns in the contingency
#'   table (must be a factor)
#' @param counts optional variable containing frequency counts for wide-format
#'   data. If not provided, data are assumed to be in long format (one row per
#'   case).
#' @param alpha significance level for merge decisions. Two categories merge
#'   only  if their weighted chi-squared distance is not significant at this
#'   level (default 0.05).
#' @param doPruning TRUE (default) or FALSE, whether to remove categories
#'   whose weight is too small to ever differ significantly from the mean
#'   profile.
#' @param showMethodInfo TRUE or FALSE (default), display detailed
#'   methodological  explanations for the SRD procedure.
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$originalTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$summaryTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pruningTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rowMergeTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rowGroupsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rowReducedTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$colMergeTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$colGroupsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$colReducedTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$reducedTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$methodInfo} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$originalTable$asDF}
#'
#' \code{as.data.frame(results$originalTable)}
#'
#' @export
chisqsrd <- function(
    data,
    rows,
    cols,
    counts,
    alpha = 0.05,
    doPruning = TRUE,
    showMethodInfo = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("chisqsrd requires jmvcore to be installed (restart may be required)")

    if ( ! missing(rows)) rows <- jmvcore::resolveQuo(jmvcore::enquo(rows))
    if ( ! missing(cols)) cols <- jmvcore::resolveQuo(jmvcore::enquo(cols))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rows), rows, NULL),
            `if`( ! missing(cols), cols, NULL),
            `if`( ! missing(counts), counts, NULL))

    for (v in rows) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in cols) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- chisqsrdOptions$new(
        rows = rows,
        cols = cols,
        counts = counts,
        alpha = alpha,
        doPruning = doPruning,
        showMethodInfo = showMethodInfo)

    analysis <- chisqsrdClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

