
# This file is automatically generated, you probably don't want to edit this

chisqstrata2x2Options <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqstrata2x2Options",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rows = NULL,
            cols = NULL,
            strata = NULL,
            counts = NULL,
            rowRef = NULL,
            colRef = NULL,
            showORAnnotation = TRUE,
            showPartialChiSq = TRUE,
            showForestPlot = TRUE,
            showDiagnosticSummary = TRUE,
            strataOrdered = FALSE,
            showTrajectoryPlot = TRUE,
            showInterpretation = TRUE,
            showMethodInfo = FALSE, ...) {

            super$initialize(
                package="ChiSquaredTools",
                name="chisqstrata2x2",
                requiresData=TRUE,
                ...)

            private$..rows <- jmvcore::OptionVariable$new(
                "rows",
                rows,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..cols <- jmvcore::OptionVariable$new(
                "cols",
                cols,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..strata <- jmvcore::OptionVariable$new(
                "strata",
                strata,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                suggested=list(
                    "continuous"))
            private$..rowRef <- jmvcore::OptionLevel$new(
                "rowRef",
                rowRef,
                variable="(rows)")
            private$..colRef <- jmvcore::OptionLevel$new(
                "colRef",
                colRef,
                variable="(cols)")
            private$..showORAnnotation <- jmvcore::OptionBool$new(
                "showORAnnotation",
                showORAnnotation,
                default=TRUE)
            private$..showPartialChiSq <- jmvcore::OptionBool$new(
                "showPartialChiSq",
                showPartialChiSq,
                default=TRUE)
            private$..showForestPlot <- jmvcore::OptionBool$new(
                "showForestPlot",
                showForestPlot,
                default=TRUE)
            private$..showDiagnosticSummary <- jmvcore::OptionBool$new(
                "showDiagnosticSummary",
                showDiagnosticSummary,
                default=TRUE)
            private$..strataOrdered <- jmvcore::OptionBool$new(
                "strataOrdered",
                strataOrdered,
                default=FALSE)
            private$..showTrajectoryPlot <- jmvcore::OptionBool$new(
                "showTrajectoryPlot",
                showTrajectoryPlot,
                default=TRUE)
            private$..showInterpretation <- jmvcore::OptionBool$new(
                "showInterpretation",
                showInterpretation,
                default=TRUE)
            private$..showMethodInfo <- jmvcore::OptionBool$new(
                "showMethodInfo",
                showMethodInfo,
                default=FALSE)

            self$.addOption(private$..rows)
            self$.addOption(private$..cols)
            self$.addOption(private$..strata)
            self$.addOption(private$..counts)
            self$.addOption(private$..rowRef)
            self$.addOption(private$..colRef)
            self$.addOption(private$..showORAnnotation)
            self$.addOption(private$..showPartialChiSq)
            self$.addOption(private$..showForestPlot)
            self$.addOption(private$..showDiagnosticSummary)
            self$.addOption(private$..strataOrdered)
            self$.addOption(private$..showTrajectoryPlot)
            self$.addOption(private$..showInterpretation)
            self$.addOption(private$..showMethodInfo)
        }),
    active = list(
        rows = function() private$..rows$value,
        cols = function() private$..cols$value,
        strata = function() private$..strata$value,
        counts = function() private$..counts$value,
        rowRef = function() private$..rowRef$value,
        colRef = function() private$..colRef$value,
        showORAnnotation = function() private$..showORAnnotation$value,
        showPartialChiSq = function() private$..showPartialChiSq$value,
        showForestPlot = function() private$..showForestPlot$value,
        showDiagnosticSummary = function() private$..showDiagnosticSummary$value,
        strataOrdered = function() private$..strataOrdered$value,
        showTrajectoryPlot = function() private$..showTrajectoryPlot$value,
        showInterpretation = function() private$..showInterpretation$value,
        showMethodInfo = function() private$..showMethodInfo$value),
    private = list(
        ..rows = NA,
        ..cols = NA,
        ..strata = NA,
        ..counts = NA,
        ..rowRef = NA,
        ..colRef = NA,
        ..showORAnnotation = NA,
        ..showPartialChiSq = NA,
        ..showForestPlot = NA,
        ..showDiagnosticSummary = NA,
        ..strataOrdered = NA,
        ..showTrajectoryPlot = NA,
        ..showInterpretation = NA,
        ..showMethodInfo = NA)
)

chisqstrata2x2Results <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqstrata2x2Results",
    inherit = jmvcore::Group,
    active = list(
        partialTablesGroup = function() private$.items[["partialTablesGroup"]],
        marginalTableHeader = function() private$.items[["marginalTableHeader"]],
        marginalTable = function() private$.items[["marginalTable"]],
        marginalORAnnotation = function() private$.items[["marginalORAnnotation"]],
        analysisResultsHeader = function() private$.items[["analysisResultsHeader"]],
        partialChiSqTable = function() private$.items[["partialChiSqTable"]],
        oddsRatioTable = function() private$.items[["oddsRatioTable"]],
        cmhTestTable = function() private$.items[["cmhTestTable"]],
        homogeneityTable = function() private$.items[["homogeneityTable"]],
        interpretationGuideHeader = function() private$.items[["interpretationGuideHeader"]],
        interpretationNote = function() private$.items[["interpretationNote"]],
        diagnosticSummary = function() private$.items[["diagnosticSummary"]],
        forestPlot = function() private$.items[["forestPlot"]],
        trajectoryPlot = function() private$.items[["trajectoryPlot"]],
        methodInfo = function() private$.items[["methodInfo"]],
        legendNote = function() private$.items[["legendNote"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Stratified Analysis (2×2×K)")
            self$add(jmvcore::Array$new(
                options=options,
                name="partialTablesGroup",
                title="Partial Tables (Strata)",
                template=jmvcore::Table$new(
                    options=options,
                    title="Partial Table",
                    columns=list()),
                clearWith=list(
                    "rows",
                    "cols",
                    "strata",
                    "counts",
                    "rowRef",
                    "colRef")))
            self$add(jmvcore::Html$new(
                options=options,
                name="marginalTableHeader",
                title="",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="marginalTable",
                clearWith=list(
                    "rows",
                    "cols",
                    "strata",
                    "counts"),
                columns=list()))
            self$add(jmvcore::Html$new(
                options=options,
                name="marginalORAnnotation",
                title="",
                visible="(showORAnnotation)",
                clearWith=list(
                    "rows",
                    "cols",
                    "strata",
                    "counts",
                    "rowRef",
                    "colRef")))
            self$add(jmvcore::Html$new(
                options=options,
                name="analysisResultsHeader",
                title="",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="partialChiSqTable",
                title="Chi-Squared Tests",
                visible="(showPartialChiSq)",
                clearWith=list(
                    "rows",
                    "cols",
                    "strata",
                    "counts"),
                columns=list(
                    list(
                        `name`="stratum", 
                        `title`="Table", 
                        `type`="text"),
                    list(
                        `name`="chisq", 
                        `title`="\u03C7\u00B2", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="pvalue", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="oddsRatioTable",
                title="Odds Ratios and Confidence Intervals",
                clearWith=list(
                    "rows",
                    "cols",
                    "strata",
                    "counts",
                    "rowRef",
                    "colRef"),
                columns=list(
                    list(
                        `name`="stratum", 
                        `title`="Table", 
                        `type`="text"),
                    list(
                        `name`="or", 
                        `title`="Odds Ratio", 
                        `type`="number"),
                    list(
                        `name`="ciLower", 
                        `title`="Lower", 
                        `superTitle`="95% CI", 
                        `type`="number"),
                    list(
                        `name`="ciUpper", 
                        `title`="Upper", 
                        `superTitle`="95% CI", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cmhTestTable",
                title="Cochran-Mantel-Haenszel Test for Conditional Independence",
                clearWith=list(
                    "rows",
                    "cols",
                    "strata",
                    "counts"),
                columns=list(
                    list(
                        `name`="test", 
                        `title`="Test", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="pvalue", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="commonOR", 
                        `title`="Common OR", 
                        `type`="number"),
                    list(
                        `name`="commonCILower", 
                        `title`="Lower", 
                        `superTitle`="95% CI", 
                        `type`="number"),
                    list(
                        `name`="commonCIUpper", 
                        `title`="Upper", 
                        `superTitle`="95% CI", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="homogeneityTable",
                title="Tests for Homogeneity of Odds Ratios",
                clearWith=list(
                    "rows",
                    "cols",
                    "strata",
                    "counts"),
                columns=list(
                    list(
                        `name`="test", 
                        `title`="Test", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="pvalue", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="interpretationGuideHeader",
                title="",
                visible="(showInterpretation)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="interpretationNote",
                title="Interpretation",
                visible="(showInterpretation)",
                clearWith=list(
                    "rows",
                    "cols",
                    "strata",
                    "counts",
                    "rowRef",
                    "colRef")))
            self$add(jmvcore::Html$new(
                options=options,
                name="diagnosticSummary",
                title="Diagnostic Summary",
                visible="(showDiagnosticSummary)",
                clearWith=list(
                    "rows",
                    "cols",
                    "strata",
                    "counts")))
            self$add(jmvcore::Image$new(
                options=options,
                name="forestPlot",
                title="Forest Plot of Odds Ratios",
                visible="(showForestPlot)",
                width=700,
                height=400,
                renderFun=".forestPlot",
                requiresData=TRUE,
                clearWith=list(
                    "rows",
                    "cols",
                    "strata",
                    "counts",
                    "rowRef",
                    "colRef")))
            self$add(jmvcore::Image$new(
                options=options,
                name="trajectoryPlot",
                title="Odds Ratio Trajectory",
                visible="(showTrajectoryPlot && strataOrdered)",
                width=700,
                height=450,
                renderFun=".trajectoryPlot",
                requiresData=TRUE,
                clearWith=list(
                    "rows",
                    "cols",
                    "strata",
                    "counts",
                    "rowRef",
                    "colRef",
                    "strataOrdered")))
            self$add(jmvcore::Html$new(
                options=options,
                name="methodInfo",
                title="Method Details",
                visible="(showMethodInfo)",
                clearWith=list(
                    "rows",
                    "cols",
                    "strata")))
            self$add(jmvcore::Html$new(
                options=options,
                name="legendNote",
                title="References"))}))

chisqstrata2x2Base <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqstrata2x2Base",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ChiSquaredTools",
                name = "chisqstrata2x2",
                version = c(1,0,0),
                options = options,
                results = chisqstrata2x2Results$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Stratified Analysis (2×2×K)
#'
#' Comprehensive stratified analysis of 2×2 contingency tables for assessing
#' conditional independence and homogeneity of odds ratios across strata.
#' 
#' For tables larger than 2×2, use the dedicated "Stratified Analysis (R×C×K)" 
#' facility, which provides Cramér's V corrected and log-linear homogeneity 
#' tests.
#' 
#' This facility performs a holistic diagnostic procedure that automatically
#' runs all core tests required for proper interpretation:
#' 
#' - Stratum-specific odds ratios with 95\% confidence intervals
#' - Chi-squared tests for each partial table and the marginal table
#' - Cochran-Mantel-Haenszel (CMH) test for conditional independence
#' - Mantel-Haenszel (MH) test for homogeneity of odds ratios
#' - Breslow-Day-Tarone (BDT) test for homogeneity of odds ratios
#' 
#' The analysis provides automated interpretation based on four diagnostic
#' scenarios that consider the joint pattern of test results. When cell counts
#' contain zeros, the Haldane-Anscombe correction (adding 0.5 to all cells)
#' is applied for odds ratio calculations and MH weights.
#' 
#' This facility requires 2×2 tables only (both row and column variables
#' must have exactly two levels).
#' 
#'
#' @examples
#' \donttest{
#' # Example with Titanic survival data
#' # Create a data frame with Class as stratifying variable
#'
#' titanic_df <- data.frame(
#'     Survival = factor(c(rep("Yes", 6), rep("No", 6))),
#'     Gender = factor(rep(c("Female", "Female", "Female",
#'                           "Male", "Male", "Male"), 2)),
#'     Class = factor(rep(c("1st", "2nd", "3rd"), 4)),
#'     Count = c(118, 146, 418, 5, 12, 110,
#'               61, 25, 75, 139, 94, 106)
#' )
#'
#' ChiSquaredTools::chisqstrata(
#'     data = titanic_df,
#'     rows = 'Survival',
#'     cols = 'Gender',
#'     strata = 'Class',
#'     counts = 'Count'
#' )
#'}
#' @param data the data as a data frame
#' @param rows a string naming the variable for rows in the 2×2 tables (must
#'   be a factor with exactly 2 levels)
#' @param cols a string naming the variable for columns in the 2×2 tables
#'   (must be a factor with exactly 2 levels)
#' @param strata a string naming the stratifying variable; each level defines
#'   one 2×2 partial table (must be a factor with 2 or more levels)
#' @param counts optional variable containing frequency counts for aggregated
#'   data. If not provided, data are assumed to be in long format (one row per
#'   case).
#' @param rowRef The row level selected as the category of interest.
#' @param colRef The column level selected as the category of interest.
#' @param showORAnnotation TRUE or FALSE (default: TRUE), display a
#'   plain-language interpretation of the odds ratio beneath each partial table
#'   and the marginal table.
#' @param showPartialChiSq TRUE or FALSE (default: TRUE), display chi-squared
#'   test results for each partial table in addition to the summary.
#' @param showForestPlot TRUE or FALSE (default: TRUE), display a forest plot
#'   showing stratum-specific odds ratios with 95\% confidence intervals and the
#'   common Mantel-Haenszel odds ratio.
#' @param showDiagnosticSummary TRUE or FALSE (default: TRUE), display a
#'   textual summary of the analytical outcome.
#' @param strataOrdered TRUE or FALSE (default: FALSE), treat the stratifying
#'   variable as having a natural ordering. When enabled, allows trajectory plot
#'   visualisation and ordered axis labels.
#' @param showTrajectoryPlot TRUE or FALSE (default: TRUE), display an odds
#'   ratio trajectory plot when the stratifying variable is marked as ordered.
#' @param showInterpretation TRUE or FALSE (default: TRUE), display the
#'   detailed interpretation guide based on the pattern of test results.
#' @param showMethodInfo TRUE or FALSE (default: FALSE), display detailed
#'   methodological  explanations for all tests performed.
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$partialTablesGroup} \tab \tab \tab \tab \tab an array of tables \cr
#'   \code{results$marginalTableHeader} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$marginalTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$marginalORAnnotation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$analysisResultsHeader} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$partialChiSqTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$oddsRatioTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cmhTestTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$homogeneityTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$interpretationGuideHeader} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$interpretationNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$diagnosticSummary} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$forestPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$trajectoryPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$methodInfo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$legendNote} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$marginalTable$asDF}
#'
#' \code{as.data.frame(results$marginalTable)}
#'
#' @export
chisqstrata2x2 <- function(
    data,
    rows,
    cols,
    strata,
    counts,
    rowRef,
    colRef,
    showORAnnotation = TRUE,
    showPartialChiSq = TRUE,
    showForestPlot = TRUE,
    showDiagnosticSummary = TRUE,
    strataOrdered = FALSE,
    showTrajectoryPlot = TRUE,
    showInterpretation = TRUE,
    showMethodInfo = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("chisqstrata2x2 requires jmvcore to be installed (restart may be required)")

    if ( ! missing(rows)) rows <- jmvcore::resolveQuo(jmvcore::enquo(rows))
    if ( ! missing(cols)) cols <- jmvcore::resolveQuo(jmvcore::enquo(cols))
    if ( ! missing(strata)) strata <- jmvcore::resolveQuo(jmvcore::enquo(strata))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rows), rows, NULL),
            `if`( ! missing(cols), cols, NULL),
            `if`( ! missing(strata), strata, NULL),
            `if`( ! missing(counts), counts, NULL))

    for (v in rows) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in cols) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in strata) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- chisqstrata2x2Options$new(
        rows = rows,
        cols = cols,
        strata = strata,
        counts = counts,
        rowRef = rowRef,
        colRef = colRef,
        showORAnnotation = showORAnnotation,
        showPartialChiSq = showPartialChiSq,
        showForestPlot = showForestPlot,
        showDiagnosticSummary = showDiagnosticSummary,
        strataOrdered = strataOrdered,
        showTrajectoryPlot = showTrajectoryPlot,
        showInterpretation = showInterpretation,
        showMethodInfo = showMethodInfo)

    analysis <- chisqstrata2x2Class$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

