
# This file is automatically generated, you probably don't want to edit this

chisqstrataRxCOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqstrataRxCOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rows = NULL,
            cols = NULL,
            strata = NULL,
            counts = NULL,
            nBootstrap = 1000,
            showResiduals = FALSE,
            showForestPlot = TRUE,
            showDiagnosticTree = TRUE,
            strataOrdered = FALSE,
            showTrajectoryPlot = TRUE,
            showInterpretation = TRUE,
            showDiagnosticSummary = TRUE,
            showMethodInfo = FALSE, ...) {

            super$initialize(
                package="ChiSquaredTools",
                name="chisqstrataRxC",
                requiresData=TRUE,
                ...)

            private$..rows <- jmvcore::OptionVariable$new(
                "rows",
                rows,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..cols <- jmvcore::OptionVariable$new(
                "cols",
                cols,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..strata <- jmvcore::OptionVariable$new(
                "strata",
                strata,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                suggested=list(
                    "continuous"))
            private$..nBootstrap <- jmvcore::OptionInteger$new(
                "nBootstrap",
                nBootstrap,
                default=1000,
                min=100,
                max=10000)
            private$..showResiduals <- jmvcore::OptionBool$new(
                "showResiduals",
                showResiduals,
                default=FALSE)
            private$..showForestPlot <- jmvcore::OptionBool$new(
                "showForestPlot",
                showForestPlot,
                default=TRUE)
            private$..showDiagnosticTree <- jmvcore::OptionBool$new(
                "showDiagnosticTree",
                showDiagnosticTree,
                default=TRUE)
            private$..strataOrdered <- jmvcore::OptionBool$new(
                "strataOrdered",
                strataOrdered,
                default=FALSE)
            private$..showTrajectoryPlot <- jmvcore::OptionBool$new(
                "showTrajectoryPlot",
                showTrajectoryPlot,
                default=TRUE)
            private$..showInterpretation <- jmvcore::OptionBool$new(
                "showInterpretation",
                showInterpretation,
                default=TRUE)
            private$..showDiagnosticSummary <- jmvcore::OptionBool$new(
                "showDiagnosticSummary",
                showDiagnosticSummary,
                default=TRUE)
            private$..showMethodInfo <- jmvcore::OptionBool$new(
                "showMethodInfo",
                showMethodInfo,
                default=FALSE)

            self$.addOption(private$..rows)
            self$.addOption(private$..cols)
            self$.addOption(private$..strata)
            self$.addOption(private$..counts)
            self$.addOption(private$..nBootstrap)
            self$.addOption(private$..showResiduals)
            self$.addOption(private$..showForestPlot)
            self$.addOption(private$..showDiagnosticTree)
            self$.addOption(private$..strataOrdered)
            self$.addOption(private$..showTrajectoryPlot)
            self$.addOption(private$..showInterpretation)
            self$.addOption(private$..showDiagnosticSummary)
            self$.addOption(private$..showMethodInfo)
        }),
    active = list(
        rows = function() private$..rows$value,
        cols = function() private$..cols$value,
        strata = function() private$..strata$value,
        counts = function() private$..counts$value,
        nBootstrap = function() private$..nBootstrap$value,
        showResiduals = function() private$..showResiduals$value,
        showForestPlot = function() private$..showForestPlot$value,
        showDiagnosticTree = function() private$..showDiagnosticTree$value,
        strataOrdered = function() private$..strataOrdered$value,
        showTrajectoryPlot = function() private$..showTrajectoryPlot$value,
        showInterpretation = function() private$..showInterpretation$value,
        showDiagnosticSummary = function() private$..showDiagnosticSummary$value,
        showMethodInfo = function() private$..showMethodInfo$value),
    private = list(
        ..rows = NA,
        ..cols = NA,
        ..strata = NA,
        ..counts = NA,
        ..nBootstrap = NA,
        ..showResiduals = NA,
        ..showForestPlot = NA,
        ..showDiagnosticTree = NA,
        ..strataOrdered = NA,
        ..showTrajectoryPlot = NA,
        ..showInterpretation = NA,
        ..showDiagnosticSummary = NA,
        ..showMethodInfo = NA)
)

chisqstrataRxCResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqstrataRxCResults",
    inherit = jmvcore::Group,
    active = list(
        partialTablesGroup = function() private$.items[["partialTablesGroup"]],
        marginalTableHeader = function() private$.items[["marginalTableHeader"]],
        marginalTable = function() private$.items[["marginalTable"]],
        analysisResultsHeader = function() private$.items[["analysisResultsHeader"]],
        stratumResultsTable = function() private$.items[["stratumResultsTable"]],
        cmhTestTable = function() private$.items[["cmhTestTable"]],
        homogeneityTable = function() private$.items[["homogeneityTable"]],
        summaryMeasureTable = function() private$.items[["summaryMeasureTable"]],
        residualsHeader = function() private$.items[["residualsHeader"]],
        residualsGroup = function() private$.items[["residualsGroup"]],
        residualsNote = function() private$.items[["residualsNote"]],
        interpretationGuideHeader = function() private$.items[["interpretationGuideHeader"]],
        interpretationNote = function() private$.items[["interpretationNote"]],
        diagnosticSummary = function() private$.items[["diagnosticSummary"]],
        forestPlot = function() private$.items[["forestPlot"]],
        trajectoryPlot = function() private$.items[["trajectoryPlot"]],
        diagnosticTree = function() private$.items[["diagnosticTree"]],
        methodInfo = function() private$.items[["methodInfo"]],
        legendNote = function() private$.items[["legendNote"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Stratified Analysis (R×C×K)")
            self$add(jmvcore::Array$new(
                options=options,
                name="partialTablesGroup",
                title="Partial Tables (Strata)",
                template=jmvcore::Table$new(
                    options=options,
                    title="Partial Table",
                    columns=list()),
                clearWith=list(
                    "rows",
                    "cols",
                    "strata",
                    "counts")))
            self$add(jmvcore::Html$new(
                options=options,
                name="marginalTableHeader",
                title="",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="marginalTable",
                clearWith=list(
                    "rows",
                    "cols",
                    "strata",
                    "counts"),
                columns=list()))
            self$add(jmvcore::Html$new(
                options=options,
                name="analysisResultsHeader",
                title="",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="stratumResultsTable",
                title="Stratum-Specific Results",
                clearWith=list(
                    "rows",
                    "cols",
                    "strata",
                    "counts",
                    "nBootstrap"),
                columns=list(
                    list(
                        `name`="stratum", 
                        `title`="Table", 
                        `type`="text"),
                    list(
                        `name`="chisq", 
                        `title`="\u03C7\u00B2", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="pvalue", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="v", 
                        `title`="V", 
                        `type`="number"),
                    list(
                        `name`="vmax", 
                        `title`="V max", 
                        `type`="number"),
                    list(
                        `name`="vcorr", 
                        `title`="V corr", 
                        `type`="number"),
                    list(
                        `name`="ciLower", 
                        `title`="Lower", 
                        `superTitle`="95% CI", 
                        `type`="number"),
                    list(
                        `name`="ciUpper", 
                        `title`="Upper", 
                        `superTitle`="95% CI", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cmhTestTable",
                title="Generalised Cochran-Mantel-Haenszel Test for Conditional Independence",
                clearWith=list(
                    "rows",
                    "cols",
                    "strata",
                    "counts"),
                columns=list(
                    list(
                        `name`="test", 
                        `title`="Test", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="pvalue", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="homogeneityTable",
                title="Test for Homogeneity of Association",
                clearWith=list(
                    "rows",
                    "cols",
                    "strata",
                    "counts"),
                columns=list(
                    list(
                        `name`="test", 
                        `title`="Test", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="G\u00B2", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="pvalue", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="summaryMeasureTable",
                title="Summary Measure",
                clearWith=list(
                    "rows",
                    "cols",
                    "strata",
                    "counts",
                    "nBootstrap"),
                columns=list(
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="ciLower", 
                        `title`="Lower", 
                        `superTitle`="95% CI", 
                        `type`="number"),
                    list(
                        `name`="ciUpper", 
                        `title`="Upper", 
                        `superTitle`="95% CI", 
                        `type`="number"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="residualsHeader",
                title="",
                visible="(showResiduals)"))
            self$add(jmvcore::Array$new(
                options=options,
                name="residualsGroup",
                title="",
                visible="(showResiduals)",
                template=jmvcore::Table$new(
                    options=options,
                    title="Residuals",
                    columns=list()),
                clearWith=list(
                    "rows",
                    "cols",
                    "strata",
                    "counts")))
            self$add(jmvcore::Html$new(
                options=options,
                name="residualsNote",
                title="",
                visible="(showResiduals)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="interpretationGuideHeader",
                title="",
                visible="(showInterpretation)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="interpretationNote",
                title="Interpretation",
                visible="(showInterpretation)",
                clearWith=list(
                    "rows",
                    "cols",
                    "strata",
                    "counts")))
            self$add(jmvcore::Html$new(
                options=options,
                name="diagnosticSummary",
                title="Diagnostic Summary",
                visible="(showDiagnosticSummary)",
                clearWith=list(
                    "rows",
                    "cols",
                    "strata",
                    "counts")))
            self$add(jmvcore::Image$new(
                options=options,
                name="forestPlot",
                title="Forest Plot of V Corrected",
                visible="(showForestPlot)",
                width=700,
                height=400,
                renderFun=".forestPlot",
                requiresData=TRUE,
                clearWith=list(
                    "rows",
                    "cols",
                    "strata",
                    "counts",
                    "nBootstrap")))
            self$add(jmvcore::Image$new(
                options=options,
                name="trajectoryPlot",
                title="V Corrected Trajectory",
                visible="(showTrajectoryPlot && strataOrdered)",
                width=700,
                height=450,
                renderFun=".trajectoryPlot",
                requiresData=TRUE,
                clearWith=list(
                    "rows",
                    "cols",
                    "strata",
                    "counts",
                    "strataOrdered",
                    "nBootstrap")))
            self$add(jmvcore::Image$new(
                options=options,
                name="diagnosticTree",
                title="Diagnostic Decision Path",
                visible="(showDiagnosticTree)",
                width=800,
                height=500,
                renderFun=".diagnosticTree",
                requiresData=TRUE,
                clearWith=list(
                    "rows",
                    "cols",
                    "strata",
                    "counts")))
            self$add(jmvcore::Html$new(
                options=options,
                name="methodInfo",
                title="Method Details",
                visible="(showMethodInfo)",
                clearWith=list(
                    "rows",
                    "cols",
                    "strata")))
            self$add(jmvcore::Html$new(
                options=options,
                name="legendNote",
                title="References"))}))

chisqstrataRxCBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqstrataRxCBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ChiSquaredTools",
                name = "chisqstrataRxC",
                version = c(1,0,0),
                options = options,
                results = chisqstrataRxCResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Stratified Analysis (R×C×K)
#'
#' Stratified analysis of R×C contingency tables for assessing conditional 
#' independence and homogeneity of association across strata.
#' 
#' This facility performs a comprehensive diagnostic procedure for tables 
#' larger than 2×2, including:
#' 
#' - Stratum-specific chi-squared tests and Cramér's V corrected with 
#'   bootstrap 95\% confidence intervals
#' - Generalised Cochran-Mantel-Haenszel (CMH) test for conditional 
#' independence
#' - Log-linear likelihood ratio test for homogeneity of association patterns
#' - Weighted average of V corrected across strata (when homogeneity holds)
#' 
#' The analysis provides automated interpretation based on the joint pattern 
#' of test results, distinguishing between conditional independence, 
#' homogeneous association, and effect modification (interaction).
#' 
#' For 2×2 tables, use the dedicated "Stratified Analysis (2×2×K)" facility, 
#' which provides odds ratios and specialised homogeneity tests.
#' 
#'
#' @examples
#' \donttest{
#' # Example with occupational data stratified by region
#'
#' occ_df <- data.frame(
#'     Education = factor(rep(c("Primary", "Secondary", "Tertiary"), 12)),
#'     Occupation = factor(rep(rep(c("Manual", "Clerical", "Professional"), each = 3), 4)),
#'     Region = factor(rep(c("North", "South", "East", "West"), each = 9)),
#'     Count = c(45, 30, 15, 25, 40, 35, 10, 20, 55,
#'               50, 25, 20, 30, 35, 40, 15, 25, 50,
#'               40, 35, 18, 28, 42, 32, 12, 18, 52,
#'               48, 28, 22, 32, 38, 38, 14, 22, 48)
#' )
#'
#' ChiSquaredTools::chisqstrataRxC(
#'     data = occ_df,
#'     rows = 'Education',
#'     cols = 'Occupation',
#'     strata = 'Region',
#'     counts = 'Count'
#' )
#'}
#' @param data the data as a data frame
#' @param rows a string naming the variable for rows in the contingency tables
#'   (must be a factor with 2 or more levels)
#' @param cols a string naming the variable for columns in the contingency
#'   tables (must be a factor with 2 or more levels)
#' @param strata a string naming the stratifying variable; each level defines
#'   one partial table (must be a factor with 2 or more levels)
#' @param counts optional variable containing frequency counts for aggregated
#'   data. If not provided, data are assumed to be in long format (one row per
#'   case).
#' @param nBootstrap number of bootstrap replicates for computing confidence
#'   intervals of V corrected (default: 1000)
#' @param showResiduals TRUE or FALSE (default: FALSE), display adjusted
#'   standardised  residuals for each partial table. Residuals exceeding ±1.96
#'   (highlighted) indicate cells contributing significantly to  the chi-squared
#'   statistic at alpha = 0.05.
#' @param showForestPlot TRUE or FALSE (default: TRUE), display a forest plot
#'   showing stratum-specific V corrected with 95\% confidence intervals and the
#'   weighted average.
#' @param showDiagnosticTree TRUE or FALSE (default: TRUE), display a visual
#'   decision tree showing the diagnostic pathway based on test results.
#' @param strataOrdered TRUE or FALSE (default: FALSE), treat the stratifying
#'   variable as having a natural ordering. When enabled, allows trajectory plot
#'   visualisation.
#' @param showTrajectoryPlot TRUE or FALSE (default: TRUE), display a V
#'   corrected trajectory plot when the stratifying variable is marked as
#'   ordered.
#' @param showInterpretation TRUE or FALSE (default: TRUE), display the
#'   detailed interpretation guide based on the pattern of test results.
#' @param showDiagnosticSummary TRUE or FALSE (default: TRUE), display a
#'   narrative diagnostic summary that explains the identified scenario and its
#'   implications.
#' @param showMethodInfo TRUE or FALSE (default: FALSE), display detailed
#'   methodological  explanations for all tests performed.
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$partialTablesGroup} \tab \tab \tab \tab \tab an array of tables \cr
#'   \code{results$marginalTableHeader} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$marginalTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$analysisResultsHeader} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$stratumResultsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cmhTestTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$homogeneityTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$summaryMeasureTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$residualsHeader} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$residualsGroup} \tab \tab \tab \tab \tab an array of tables \cr
#'   \code{results$residualsNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$interpretationGuideHeader} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$interpretationNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$diagnosticSummary} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$forestPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$trajectoryPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$diagnosticTree} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$methodInfo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$legendNote} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$marginalTable$asDF}
#'
#' \code{as.data.frame(results$marginalTable)}
#'
#' @export
chisqstrataRxC <- function(
    data,
    rows,
    cols,
    strata,
    counts,
    nBootstrap = 1000,
    showResiduals = FALSE,
    showForestPlot = TRUE,
    showDiagnosticTree = TRUE,
    strataOrdered = FALSE,
    showTrajectoryPlot = TRUE,
    showInterpretation = TRUE,
    showDiagnosticSummary = TRUE,
    showMethodInfo = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("chisqstrataRxC requires jmvcore to be installed (restart may be required)")

    if ( ! missing(rows)) rows <- jmvcore::resolveQuo(jmvcore::enquo(rows))
    if ( ! missing(cols)) cols <- jmvcore::resolveQuo(jmvcore::enquo(cols))
    if ( ! missing(strata)) strata <- jmvcore::resolveQuo(jmvcore::enquo(strata))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rows), rows, NULL),
            `if`( ! missing(cols), cols, NULL),
            `if`( ! missing(strata), strata, NULL),
            `if`( ! missing(counts), counts, NULL))

    for (v in rows) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in cols) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in strata) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- chisqstrataRxCOptions$new(
        rows = rows,
        cols = cols,
        strata = strata,
        counts = counts,
        nBootstrap = nBootstrap,
        showResiduals = showResiduals,
        showForestPlot = showForestPlot,
        showDiagnosticTree = showDiagnosticTree,
        strataOrdered = strataOrdered,
        showTrajectoryPlot = showTrajectoryPlot,
        showInterpretation = showInterpretation,
        showDiagnosticSummary = showDiagnosticSummary,
        showMethodInfo = showMethodInfo)

    analysis <- chisqstrataRxCClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

